# Generated by Django 4.2.5 on 2024-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('employee', 'employee'), ('teamlead', 'teamlead')], default='admin', max_length=50),
        ),
    ]
