# Generated by Django 4.2.5 on 2024-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(),
        ),
    ]
