# Generated by Django 4.2.5 on 2024-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_alter_meeting_date_alter_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
